### ISSUE TITLE
Question about training period of ssl

### ISSUE THREAD

**Issue by ghost** [megagonlabs/sudowoodo#4]
Hi! Thank you for your hard work! When I run the code for em datasets, I found that in the ssl part, that is, the part of pre-training comparative learning model, two epoch will be automatically skipped. The situation is as follows. I wonder what the reason is. Looking forward to your reply.
![11](https://github.com/megagonlabs/sudowoodo/assets/144320879/92e2dfd6-438d-4f69-8b26-c6c8e7a654e5)

**Comment by RunhuiWang** [comment]
Hi, thanks for your interest in our work! What hyper parameters are you using?

**Comment by ghost** [comment]
> Hi, thanks for your interest in our work! What hyper parameters are you using?

Thank you for your reply. I chose the following parameters to run this experiment:
--task_type em
--task DBLP-ACM
--logdir result_em/
--ssl_method combined
--bootstrap
--clustering
--multiplier 10
--batch_size 64
--lr 5e-5
--lm roberta
--n_ssl_epochs 3
--n_epochs 50
--max_len 128
--da cutoff
--size 500
--fp16
--run_id 4
And other parameters in the code are consistent with your code. Looking forward to your reply.

**Comment by RunhuiWang** [comment]
Hi lllmmmaaa, I don't think two epochs are skipped. Can you double check how much time these epochs take to finish?
